# Generated by Django 2.2.5 on 2019-12-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='Employee',
        ),
    ]
