# Generated by Django 3.0.1 on 2019-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dphotoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(blank=True, default='', max_length=200)),
                ('date', models.DateTimeField(default='')),
            ],
        ),
    ]
