# Generated by Django 2.2.3 on 2019-07-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
