# Generated by Django 2.2.3 on 2019-07-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qu_id',
            new_name='qu_txt',
        ),
    ]
