# Generated by Django 3.0 on 2019-12-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('offer', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
