# Generated by Django 3.0 on 2019-12-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travello',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
